project_id = "vgdreuwmisludqxphsph"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"

[storage]
file_size_limit = "50MiB"

# Edge functions configuration
# This enables the functions to be deployed automatically
[functions]
[functions.send-delivery-tracking]
verify_jwt = true
[functions.update-delivery-status]
verify_jwt = true
[functions.upload-delivery-photo]
verify_jwt = true
[functions.capture-signature]
verify_jwt = true
[functions.sync-calendar]
verify_jwt = true